; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags = -Wall -O2 -DCORE_DEBUG_LEVEL=0
board_build.f_cpu = 240000000L
lib_deps = 
	mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display
	adafruit/Adafruit GFX Library
	adafruit/RTClib @ ^2.1.4
	olikraus/U8g2_for_Adafruit_GFX @ ^1.8.0
	olikraus/U8g2 @ ^2.34.22
	mathieucarbou/AsyncTCP @ ^3.2.3
	mathieucarbou/ESPAsyncWebServer @ ^3.1.5
	beegee-tokyo/DHT sensor library for ESPx@^1.19
	bblanchon/ArduinoJson @ ^7.0.0
