/**
 * @file WebUI_Static.h
 * @brief Compiled-in HTML/CSS/JS for the web configuration portal.
 *
 * @author finntrannn (finntrannn.id.vn)
 * @github https://github.com/finntrannn
 */

#pragma once

#include "WebStrings.h"

const char HTML_UI_STATIC[] PROGMEM = 
"\n"
"<!DOCTYPE html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no'>\n"
"<title>" kPageTitle "</title>\n"
"<style>\n"
"*{box-sizing:border-box;}\n"
"body{font-family:'Segoe UI',Roboto,Helvetica,sans-serif;margin:0;padding:0;background:#f0f2f5;color:#1c1e21;display:flex;height:100vh;overflow:hidden;}\n"
"\n"
".sidebar{width:260px;background:#fff;display:flex;flex-direction:column;overflow-y:auto;box-shadow:2px 0 8px rgba(0,0,0,.05);z-index:20;border-right:1px solid #ddd;}\n"
".sidebar-header{padding:20px;color:#0056b3;display:flex;align-items:center;border-bottom:1px solid #eee;}\n"
".sidebar-header h2{margin:0;font-size:18px;font-weight:700;}\n"
"\n"
".dropdown-btn{background:none;border:none;color:#1c1e21;padding:14px 18px;text-align:left;font-size:14px;cursor:pointer;font-weight:700;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #f0f2f5;outline:none;transition:.15s;}\n"
".dropdown-btn:hover{background:#f5f6f7;}\n"
".dropdown-icon{transition:transform .2s;font-size:11px;color:#999;}\n"
".dropdown-active .dropdown-icon{transform:rotate(180deg);color:#0056b3;}\n"
".dropdown-container{display:none;flex-direction:column;background:#fafafa;}\n"
"\n"
".tab-btn{background:none;border:none;color:#4b4f56;padding:12px 18px 12px 36px;text-align:left;font-size:13px;cursor:pointer;border-left:3px solid transparent;font-weight:600;transition:.15s;}\n"
".tab-btn:hover{background:#f0f2f5;color:#0056b3;}\n"
".tab-btn.active{background:#e7f3ff;color:#0056b3;border-left:3px solid #0056b3;}\n"
"\n"
".flat-btn{background:none;border:none;color:#4b4f56;padding:14px 18px;text-align:left;font-size:14px;cursor:pointer;font-weight:700;border-bottom:1px solid #f0f2f5;border-left:3px solid transparent;transition:.15s;}\n"
".flat-btn:hover{background:#f5f6f7;color:#0056b3;}\n"
".flat-btn.active{background:#e7f3ff;color:#0056b3;border-left:3px solid #0056b3;}\n"
"\n"
".main-content{flex:1;padding:24px;overflow-y:auto;display:flex;flex-direction:column;position:relative;}\n"
".top-actions{display:flex;gap:10px;justify-content:flex-end;margin-bottom:20px;padding:12px;background:#fff;border-radius:10px;border:1px solid #ddd;box-shadow:0 1px 3px rgba(0,0,0,.05);}\n"
".btn-small{padding:9px 16px;font-size:13px;font-weight:bold;border-radius:6px;border:none;cursor:pointer;transition:.2s;color:#fff;}\n"
".btn-small:hover{opacity:.9;transform:translateY(-1px);}\n"
".tab-content{display:none;animation:fadeIn .25s ease;}\n"
"@keyframes fadeIn{from{opacity:0;transform:translateY(4px);}to{opacity:1;transform:translateY(0);}}\n"
".grid{display:grid;gap:18px;grid-template-columns:1fr;}\n"
"@media(min-width:1000px){.grid{grid-template-columns:1fr 1fr;}}\n"
"\n"
".section{background:#fff;padding:22px;border-radius:12px;height:fit-content;box-shadow:0 2px 8px rgba(0,0,0,.04);border:1px solid #eaeaea;}\n"
".section h3{margin:0 0 18px;font-size:16px;color:#1c1e21;border-bottom:2px solid #f0f2f5;padding-bottom:10px;font-weight:700;}\n"
"input:not([type='file']):not([type='radio']):not([type='checkbox']):not([type='range']),select{box-sizing:border-box;width:100%;padding:10px 8px 10px 10px;margin:4px 0 16px;border-radius:8px;border:1px solid #ccd0d5;background:#fff;color:#1c1e21;font-size:15px;outline:none;transition:border .2s;}\n"
"input[type='color']{height:46px;padding:3px;cursor:pointer;}\n"
"input[type='color']::-webkit-color-swatch-wrapper{padding:0;}\n"
"input[type='color']::-webkit-color-swatch{border:none;border-radius:5px;}\n"
"input:focus,select:focus{border-color:#0056b3;}\n"
"\n"
".sg{display:flex;align-items:center;gap:8px;margin:4px 0 16px;}\n"
".sg input[type='range']{flex:1 1 auto;min-width:60px;height:6px;margin:0;cursor:pointer;accent-color:#0056b3;}\n"
".sg input[type='number']{flex:0 0 64px;width:64px;margin:0;text-align:center;padding:6px 4px;font-size:13px;border-radius:6px;border:1px solid #ccd0d5;}\n"
"\n"
"label{display:block;font-size:13px;color:#606770;font-weight:600;margin-bottom:4px;}\n"
".radio-group{display:flex;flex-direction:column;gap:8px;margin-bottom:16px;}\n"
".radio-group label{display:flex;align-items:center;padding:14px;border-radius:8px;cursor:pointer;background:#fdfdfd;border:1px solid #ddd;margin:0;font-weight:600;font-size:14px;transition:.2s;color:#4b4f56;}\n"
".radio-group label.selected{background:#e7f3ff;border-color:#0056b3;color:#0056b3;}\n"
".radio-group input{margin:0 10px 0 0;width:16px;height:16px;accent-color:#0056b3;}\n"
".chk{display:flex;align-items:center;cursor:pointer;margin:10px 0;background:#fdfdfd;padding:14px;border-radius:8px;border:1px solid #ddd;gap:10px;font-weight:600;font-size:13px;color:#1c1e21;transition:.2s;}\n"
".chk:hover{background:#f5f6f7;}\n"
".chk input{width:18px;height:18px;margin:0;cursor:pointer;accent-color:#0056b3;}\n"
".note{font-size:12px;color:#777;margin-top:-6px;margin-bottom:16px;display:block;line-height:1.4;}\n"
"progress{width:100%;height:18px;margin-top:8px;display:none;}\n"
"\n"
".hamburger{display:none;background:#0056b3;color:#fff;border:none;border-radius:8px;width:40px;height:40px;flex-shrink:0;font-size:22px;cursor:pointer;box-shadow:0 2px 6px rgba(0,0,0,.15);line-height:1;transition:opacity .2s;margin-bottom:10px;}\n"
".overlay{display:none;position:fixed;inset:0;background:rgba(0,0,0,.35);z-index:15;}\n"
"\n"
"#toast{position:fixed;bottom:20px;right:20px;background:#28a745;color:white;padding:15px 25px;border-radius:8px;box-shadow:0 4px 12px rgba(0,0,0,.15);font-weight:bold;z-index:9999;transition:0.3s;opacity:0;transform:translateY(20px);pointer-events:none;}\n"
"#toast.show{opacity:1;transform:translateY(0);}\n"
"#toast.error{background:#dc3545;}\n"
"\n"
"@media(max-width:768px){\n"
"  .hamburger{display:block;}\n"
"  .sidebar{position:fixed;left:-300px;top:0;bottom:0;width:260px;transition:left .25s ease;z-index:30;}\n"
"  .sidebar.open{left:0;}\n"
"  .sidebar.open~.overlay+.main-content .hamburger,.hamburger.hidden{opacity:0;pointer-events:none;}\n"
"  .overlay.show{display:block;}\n"
"  .main-content{padding:14px;}\n"
"  .top-actions{flex-wrap:wrap;gap:6px;}\n"
"  .top-actions>button{flex:1;min-width:0;}\n"
"  .btn-small{width:100%;padding:10px 6px;font-size:12px;}\n"
"}\n"
"</style>\n"
"<script>\n"
"let stateData = {};\n"
"\n"
"function initApp() {\n"
"  const urlParams = new URLSearchParams(window.location.search);\n"
"  const tab = urlParams.get('tab') || 'sys';\n"
"  opentabByString(tab);\n"
"\n"
"  fetch('/api/config').then(r => r.json()).then(data => {\n"
"    stateData = data;\n"
"    populateForm();\n"
"  }).catch(e => showToast(\"Lỗi tải cấu hình (Mất kết nối)\", true));\n"
"}\n"
"\n"
"function showToast(msg, isError) {\n"
"  var t = document.getElementById(\"toast\");\n"
"  t.innerText = msg;\n"
"  t.className = isError ? \"error show\" : \"show\";\n"
"  setTimeout(()=>t.className=\"\", 3000);\n"
"}\n"
"\n"
"function populateForm() {\n"
"  const d = stateData;\n"
"  document.querySelector('[name=staSSID]').value = d.staSSID || '';\n"
"  document.querySelector('[name=staPass]').value = d.staPass || '';\n"
"  document.querySelector('[name=apSSID]').value = d.apSSID || '';\n"
"  document.querySelector('[name=apPass]').value = d.apPass || '';\n"
"\n"
"  document.querySelector('[name=ledState]').checked = d.ledState;\n"
"  document.querySelector('[name=splashState]').checked = d.splashState;\n"
"  document.querySelector('[name=splashText]').value = d.splashText || '';\n"
"  document.querySelector('[name=wifiIcon]').checked = d.wifiIcon;\n"
"  syncSlider('brightness', d.brightness);\n"
"  \n"
"  selRadio('screenMode', d.screenMode);\n"
"\n"
"  document.querySelector('[name=showSecCD]').checked = d.showSecCD;\n"
"  document.querySelector('[name=showMessage]').checked = d.showMessage;\n"
"  document.querySelector('[name=rainbowState]').checked = d.rainbowState;\n"
"  \n"
"  if (d.targetEpoch) {\n"
"      const date = new Date(d.targetEpoch * 1000);\n"
"      const iso = new Date(date.getTime() - (date.getTimezoneOffset() * 60000)).toISOString().slice(0, 16);\n"
"      document.querySelector('[name=datetime]').value = iso;\n"
"  }\n"
"  document.querySelector('[name=customText]').value = d.customText || '';\n"
"  syncSlider('textSpeed', d.textSpeed);\n"
"  syncSlider('rainbowSpeed', d.rainbowSpeed);\n"
"  document.querySelector('[name=cdDaysClr]').value = d.cdDaysColor || '#ffff00';\n"
"  document.querySelector('[name=cdTimeClr]').value = d.cdTimeColor || '#00ffff';\n"
"\n"
"  document.querySelector('[name=sensorBg]').checked = d.sensorBg;\n"
"  document.querySelector('[name=openMeteoEn]').checked = d.openMeteoEn;\n"
"  document.querySelector('[name=weaLat]').value = d.weaLat !== undefined ? d.weaLat : 21.0285;\n"
"  document.querySelector('[name=weaLon]').value = d.weaLon !== undefined ? d.weaLon : 105.8542;\n"
"\n"
"  document.querySelector('[name=showYear]').checked = d.showYear;\n"
"  document.querySelector('[name=shortYear]').checked = d.shortYear;\n"
"  document.querySelector('[name=showSecDT]').checked = d.showSecDT;\n"
"  document.querySelector('[name=dateSep]').value = d.dateSep || '0';\n"
"\n"
"  document.querySelector('[name=txtScroll]').checked = d.txtScroll;\n"
"  document.querySelector('[name=txtContent]').value = d.txtContent || '';\n"
"  syncSlider('txtSpeed', d.txtSpeed);\n"
"  syncSlider('txtSize', d.txtSize);\n"
"  document.querySelector('[name=txtColor]').value = d.txtColor || '#00FF00';\n"
"\n"
"  document.querySelector('[name=autoCycle]').checked = d.autoCycle;\n"
"  document.querySelector('[name=cycleSeq]').value = d.cycleSeq || '';\n"
"  syncSlider('timer0', d.timer0);\n"
"  syncSlider('timer1', d.timer1);\n"
"  syncSlider('timer2', d.timer2);\n"
"  syncSlider('timer3', d.timer3);\n"
"  syncSlider('timer4', d.timer4);\n"
"\n"
"  document.querySelector('[name=fwScheds]').value = d.fwScheds || '';\n"
"\n"
"  document.querySelector('[name=spinMin]').value = d.spinMin;\n"
"  document.querySelector('[name=spinMax]').value = d.spinMax;\n"
"  syncSlider('spinDur', d.spinDur);\n"
"}\n"
"\n"
"function syncSlider(name, val) {\n"
"  var r = document.getElementById('r_' + name);\n"
"  var n = document.getElementById('n_' + name);\n"
"  if (r) r.value = val;\n"
"  if (n) n.value = val;\n"
"}\n"
"\n"
"function saveConfig(e) {\n"
"  e.preventDefault();\n"
"  const formData = new FormData(document.getElementById('mForm'));\n"
"  \n"
"  fetch('/save', {\n"
"    method: 'POST',\n"
"    body: new URLSearchParams(formData)\n"
"  })\n"
"  .then(r => r.json())\n"
"  .then(data => {\n"
"    if (data.status === 'ok') showToast(\"Đã lưu cấu hình\", false);\n"
"    else showToast(\"Lỗi lưu cấu hình\", true);\n"
"  }).catch(e => showToast(\"Mất kết nối\", true));\n"
"}\n"
"\n"
"function reqCmd(url) {\n"
"  fetch(url, {method:'POST'}).then(r=>{\n"
"      showToast(\"Đã gửi lệnh\", false);\n"
"  });\n"
"}\n"
"\n"
"function opentabByString(t) {\n"
"  let parent = \"\";\n"
"  if ([\"cd\",\"sensor\",\"datetime\",\"text\",\"spinner\",\"scr_gen\"].includes(t)) parent = \"dd_disp\";\n"
"  opentab(t, parent);\n"
"}\n"
"\n"
"function toggleMenu(){\n"
"  var s=document.getElementById('sidebar');\n"
"  var h=document.getElementById('hbtn');\n"
"  s.classList.toggle('open');\n"
"  document.getElementById('overlay').classList.toggle('show');\n"
"  if(s.classList.contains('open')){h.classList.add('hidden');}else{h.classList.remove('hidden');}\n"
"}\n"
"function closeMenu(){\n"
"  document.getElementById('sidebar').classList.remove('open');\n"
"  document.getElementById('overlay').classList.remove('show');\n"
"  document.getElementById('hbtn').classList.remove('hidden');\n"
"}\n"
"function toggleDropdown(btn){\n"
"  btn.classList.toggle(\"dropdown-active\");\n"
"  var c=btn.nextElementSibling;\n"
"  c.style.display=c.style.display===\"flex\"?\"none\":\"flex\";\n"
"}\n"
"function opentab(t,parentBtnId){\n"
"  var c=document.getElementsByClassName('tab-content');\n"
"  for(var i=0;i<c.length;i++) c[i].style.display='none';\n"
"  var b=document.getElementsByClassName('tab-btn');\n"
"  for(var j=0;j<b.length;j++) b[j].classList.remove('active');\n"
"  var f=document.getElementsByClassName('flat-btn');\n"
"  for(var k=0;k<f.length;k++) f[k].classList.remove('active');\n"
"  document.getElementById('tab_'+t).style.display='block';\n"
"  var btn=document.getElementById('btn_'+t);\n"
"  if(btn) btn.classList.add('active');\n"
"  var a=document.getElementById('activeTabInput');\n"
"  if(a)a.value=t;\n"
"  if(parentBtnId){\n"
"    var p=document.getElementById(parentBtnId);\n"
"    if(p&&p.nextElementSibling&&p.nextElementSibling.style.display!==\"flex\"){\n"
"      p.classList.add(\"dropdown-active\");\n"
"      p.nextElementSibling.style.display=\"flex\";\n"
"    }\n"
"  }\n"
"  history.replaceState(null, '', '?tab=' + t);\n"
"  if(window.innerWidth<=768) closeMenu();\n"
"}\n"
"function selRadio(name,val){\n"
"  var l=document.getElementsByTagName('label');\n"
"  for(var i=0;i<l.length;i++) if(l[i].getAttribute('data-rn')===name)l[i].className='';\n"
"  document.getElementById('lbl_'+name+'_'+val).className='selected';\n"
"  \n"
"  var rad = document.querySelector('input[name=\"'+name+'\"][value=\"'+val+'\"]');\n"
"  if(rad) rad.checked = true;\n"
"}\n"
"function syncS(id,v){document.getElementById(id).value=v;}\n"
"\n"
"function doSpin(btn) {\n"
"  var durInput = document.querySelector('input[name=\"spinDur\"]');\n"
"  var dur = (durInput ? parseInt(durInput.value) : 5) * 1000;\n"
"  btn.disabled = true;\n"
"  var oldText = btn.innerText;\n"
"  btn.innerText = \"Đang quay...\";\n"
"  btn.style.opacity = \"0.5\";\n"
"  fetch(\"/spin\", {method:\"POST\"});\n"
"  setTimeout(function() {\n"
"    btn.disabled = false;\n"
"    btn.innerText = oldText;\n"
"    btn.style.opacity = \"1\";\n"
"  }, dur + 2500);\n"
"}\n"
"function doSpinReset(btn) {\n"
"  fetch(\"/spin-reset\", {method:\"POST\"});\n"
"}\n"
"function uploadFirmware(){\n"
"  var f=document.getElementById('firmwareInput');\n"
"  if(!f.files.length){alert('Chọn file .bin!');return;}\n"
"  var d=new FormData();d.append('update',f.files[0]);\n"
"  var x=new XMLHttpRequest(),p=document.getElementById('uploadProgress'),s=document.getElementById('statusMsg');\n"
"  p.style.display='block';\n"
"  x.upload.addEventListener('progress',function(e){var pct=Math.round(e.loaded/e.total*100);p.value=pct;s.innerText='" kOtaUploading "'+pct+'%';});\n"
"  x.addEventListener('load',function(){\n"
"    if(x.status===200){s.innerText='" kOtaSuccess "';s.style.color='green';setTimeout(function(){window.location.reload();},8000);}\n"
"    else{s.innerText='Lỗi: '+x.status;s.style.color='red';}\n"
"  });\n"
"  x.addEventListener('error',function(){s.innerText='" kOtaError "';s.style.color='red';});\n"
"  x.open('POST','/update');x.send(d);\n"
"}\n"
"\n"
"window.onload = initApp;\n"
"</script>\n"
"</head><body>\n"
"<div id=\"toast\"></div>\n"
"<div class='overlay' id='overlay' onclick='closeMenu()'></div>\n"
"<div class='sidebar' id='sidebar'>\n"
"  <div class='sidebar-header'><h2>" kSidebarTitle "</h2></div>\n"
"  <button type='button' class='dropdown-btn' onclick='toggleDropdown(this)' id='dd_disp'>" kNavDisplay " <span class='dropdown-icon'>&#9660;</span></button>\n"
"  <div class='dropdown-container'>\n"
"    <button type='button' id='btn_scr_gen' class='tab-btn' onclick='opentab(\"scr_gen\",\"dd_disp\")'>" kNavGeneral "</button>\n"
"    <button type='button' id='btn_cd' class='tab-btn' onclick='opentab(\"cd\",\"dd_disp\")'>" kNavCountdown "</button>\n"
"    <button type='button' id='btn_sensor' class='tab-btn' onclick='opentab(\"sensor\",\"dd_disp\")'>" kNavSensor "</button>\n"
"    <button type='button' id='btn_datetime' class='tab-btn' onclick='opentab(\"datetime\",\"dd_disp\")'>" kNavDateTime "</button>\n"
"    <button type='button' id='btn_text' class='tab-btn' onclick='opentab(\"text\",\"dd_disp\")'>" kNavText "</button>\n"
"    <button type='button' id='btn_spinner' class='tab-btn' onclick='opentab(\"spinner\",\"dd_disp\")'>" kNavSpinner "</button>\n"
"  </div>\n"
"  <button type='button' id='btn_sys' class='flat-btn' onclick='opentab(\"sys\")'>" kNavWifi "</button>\n"
"  <button type='button' id='btn_auto' class='flat-btn' onclick='opentab(\"auto\")'>" kNavAutomation "</button>\n"
"  <button type='button' id='btn_ota' class='flat-btn' onclick='opentab(\"ota\")'>" kNavOta "</button>\n"
"</div>\n"
"\n"
"<div class='main-content'>\n"
"  <button class='hamburger' id='hbtn' onclick='toggleMenu()'>&#9776;</button>\n"
"  <div class='top-actions'>\n"
"    <button type='submit' form='mForm' class='btn-small' style='background:#0056b3;'>" kBtnSave "</button>\n"
"    <button type='button' onclick='reqCmd(\"/showsplash\")' class='btn-small' style='background:#f39c12;'>" kBtnTestSplash "</button>\n"
"    <button type='button' onclick='if(confirm(\"" kConfirmRestart "\")) reqCmd(\"/restart\")' class='btn-small' style='background:#dc3545;'>" kBtnRestart "</button>\n"
"  </div>\n"
"\n"
"  <form id='mForm' onsubmit='saveConfig(event)'>\n"
"    <input type='hidden' id='activeTabInput' name='activeTab' value='sys'>\n"
"\n"
"    <div id='tab_sys' class='tab-content'><div class='grid'>\n"
"      <div class='section'><h3>" kWifiStaTitle "</h3>\n"
"        <label>" kWifiStaSsid "</label><input type='text' name='staSSID' required>\n"
"        <label>" kWifiStaPass "</label><input type='text' name='staPass'>\n"
"      </div>\n"
"      <div class='section'><h3>" kWifiApTitle "</h3>\n"
"        <label>" kWifiApSsid "</label><input type='text' name='apSSID' required>\n"
"        <label>" kWifiApPass "</label><input type='text' name='apPass' required>\n"
"      </div>\n"
"    </div></div>\n"
"\n"
"    <div id='tab_scr_gen' class='tab-content'><div class='grid'>\n"
"      <div class='section'><h3>" kNavGeneral "</h3>\n"
"        <label class='chk'><input type='checkbox' name='ledState' value='1'> " kGenLedOn "</label>\n"
"        <label class='chk'><input type='checkbox' name='splashState' value='1'> " kGenSplashOn "</label>\n"
"        <label>" kGenSplashText "</label><input type='text' name='splashText' maxlength='20'>\n"
"        <label class='chk'><input type='checkbox' name='wifiIcon' value='1'> " kGenWifiIcon "</label>\n"
"        <label>" kGenBrightness "</label>\n"
"        <div class='sg'><input type='range' id='r_brightness' name='brightness' min='1' max='255' oninput='syncS(\"n_brightness\", this.value)'><input type='number' id='n_brightness' min='1' max='255' oninput='syncS(\"r_brightness\", this.value)'></div>\n"
"      </div>\n"
"      <div class='section'><h3>" kGenScreenTitle "</h3>\n"
"        <span class='note'>" kGenScreenNote "</span>\n"
"        <div class='radio-group'>\n"
"          <label data-rn='screenMode' id='lbl_screenMode_0' onclick='selRadio(\"screenMode\",0)'><input type='radio' name='screenMode' value='0'> " kScrCountdown "</label>\n"
"          <label data-rn='screenMode' id='lbl_screenMode_1' onclick='selRadio(\"screenMode\",1)'><input type='radio' name='screenMode' value='1'> " kScrSensor "</label>\n"
"          <label data-rn='screenMode' id='lbl_screenMode_2' onclick='selRadio(\"screenMode\",2)'><input type='radio' name='screenMode' value='2'> " kScrDateTime "</label>\n"
"          <label data-rn='screenMode' id='lbl_screenMode_3' onclick='selRadio(\"screenMode\",3)'><input type='radio' name='screenMode' value='3'> " kScrText "</label>\n"
"          <label data-rn='screenMode' id='lbl_screenMode_4' onclick='selRadio(\"screenMode\",4)'><input type='radio' name='screenMode' value='4'> " kScrSpinner "</label>\n"
"        </div>\n"
"      </div>\n"
"    </div></div>\n"
"\n"
"    <div id='tab_cd' class='tab-content'><div class='grid'>\n"
"      <div class='section'><h3>" kCdTitle "</h3>\n"
"        <label class='chk'><input type='checkbox' name='showSecCD' value='1'> " kCdShowSec "</label>\n"
"        <label class='chk'><input type='checkbox' name='showMessage' value='1'> " kCdShowMsg "</label>\n"
"        <label class='chk'><input type='checkbox' name='rainbowState' value='1'> " kCdRainbow "</label>\n"
"        <label>" kCdTarget "</label><input type='datetime-local' name='datetime' required>\n"
"        <label>" kCdMessage "</label><input type='text' name='customText'>\n"
"        <label>" kCdTextSpeed "</label>\n"
"        <div class='sg'><input type='range' id='r_textSpeed' name='textSpeed' min='1' max='10' oninput='syncS(\"n_textSpeed\", this.value)'><input type='number' id='n_textSpeed' min='1' max='10' oninput='syncS(\"r_textSpeed\", this.value)'></div>\n"
"        <label>" kCdRainbowSpeed "</label>\n"
"        <div class='sg'><input type='range' id='r_rainbowSpeed' name='rainbowSpeed' min='1' max='10' oninput='syncS(\"n_rainbowSpeed\", this.value)'><input type='number' id='n_rainbowSpeed' min='1' max='10' oninput='syncS(\"r_rainbowSpeed\", this.value)'></div>\n"
"      </div>\n"
"      <div class='section'><h3>" kCdColorTitle "</h3>\n"
"        <label>" kCdDaysColor "</label><input type='color' name='cdDaysClr'>\n"
"        <label>" kCdTimeColor "</label><input type='color' name='cdTimeClr'>\n"
"      </div>\n"
"    </div></div>\n"
"\n"
"    <div id='tab_sensor' class='tab-content'><div class='grid'>\n"
"      <div class='section'><h3>" kSenTitle "</h3>\n"
"        <label class='chk'><input type='checkbox' name='sensorBg' value='1'> " kSenBg "</label>\n"
"        <h3 style='margin-top:16px; border-bottom:none; margin-bottom:5px;'>" kSenWeatherTitle "</h3>\n"
"        <label class='chk'><input type='checkbox' name='openMeteoEn' value='1'> " kSenOpenMeteo "</label>\n"
"        <span class='note'>" kSenWeatherNote "</span>\n"
"        <label>" kSenLat "</label><input type='number' step='any' name='weaLat' required>\n"
"        <label>" kSenLon "</label><input type='number' step='any' name='weaLon' required>\n"
"      </div>\n"
"    </div></div>\n"
"\n"
"    <div id='tab_datetime' class='tab-content'><div class='grid'>\n"
"      <div class='section'><h3>" kDtTitle "</h3>\n"
"        <label class='chk'><input type='checkbox' name='showYear' value='1'> " kDtShowYear "</label>\n"
"        <label class='chk'><input type='checkbox' name='shortYear' value='1'> " kDtShortYear "</label>\n"
"        <label class='chk'><input type='checkbox' name='showSecDT' value='1'> " kDtShowSec "</label>\n"
"        <label>" kDtSeparator "</label>\n"
"        <select name='dateSep'>\n"
"          <option value='0'>" kDtSepSlash "</option>\n"
"          <option value='1'>" kDtSepDot "</option>\n"
"          <option value='2'>" kDtSepDash "</option>\n"
"        </select>\n"
"      </div>\n"
"    </div></div>\n"
"\n"
"    <div id='tab_text' class='tab-content'><div class='grid'>\n"
"      <div class='section'><h3>" kTxtTitle "</h3>\n"
"        <label class='chk'><input type='checkbox' name='txtScroll' value='1'> " kTxtScroll "</label>\n"
"        <label>" kTxtContent "</label><input type='text' name='txtContent'>\n"
"        <label>" kTxtSpeed "</label>\n"
"        <div class='sg'><input type='range' id='r_txtSpeed' name='txtSpeed' min='1' max='10' oninput='syncS(\"n_txtSpeed\", this.value)'><input type='number' id='n_txtSpeed' min='1' max='10' oninput='syncS(\"r_txtSpeed\", this.value)'></div>\n"
"        <label>" kTxtSize "</label>\n"
"        <div class='sg'><input type='range' id='r_txtSize' name='txtSize' min='1' max='4' oninput='syncS(\"n_txtSize\", this.value)'><input type='number' id='n_txtSize' min='1' max='4' oninput='syncS(\"r_txtSize\", this.value)'></div>\n"
"        <label>" kTxtColor "</label><input type='color' name='txtColor'>\n"
"      </div>\n"
"    </div></div>\n"
"\n"
"    <div id='tab_auto' class='tab-content'><div class='grid'>\n"
"      <div class='section'><h3>" kAutoTitle "</h3>\n"
"        <label class='chk'><input type='checkbox' name='autoCycle' value='1'> " kAutoEnable "</label>\n"
"        <span class='note'>" kAutoNote "</span>\n"
"        <label>" kAutoSeqLabel "</label><input type='text' name='cycleSeq' placeholder='0,1,2,3,4'>\n"
"        <h3 style='margin-top:20px;'>" kAutoTimersTitle "</h3>\n"
"        <label>" kScrCountdown ":</label><div class='sg'><input type='range' id='r_timer0' name='timer0' min='0' max='120' oninput='syncS(\"n_timer0\", this.value)'><input type='number' id='n_timer0' min='0' max='120' oninput='syncS(\"r_timer0\", this.value)'></div>\n"
"        <label>" kTimerSensor ":</label><div class='sg'><input type='range' id='r_timer1' name='timer1' min='0' max='120' oninput='syncS(\"n_timer1\", this.value)'><input type='number' id='n_timer1' min='0' max='120' oninput='syncS(\"r_timer1\", this.value)'></div>\n"
"        <label>" kTimerDateTime ":</label><div class='sg'><input type='range' id='r_timer2' name='timer2' min='0' max='120' oninput='syncS(\"n_timer2\", this.value)'><input type='number' id='n_timer2' min='0' max='120' oninput='syncS(\"r_timer2\", this.value)'></div>\n"
"        <label>" kTimerText ":</label><div class='sg'><input type='range' id='r_timer3' name='timer3' min='0' max='120' oninput='syncS(\"n_timer3\", this.value)'><input type='number' id='n_timer3' min='0' max='120' oninput='syncS(\"r_timer3\", this.value)'></div>\n"
"        <label>" kTimerSpinner ":</label><div class='sg'><input type='range' id='r_timer4' name='timer4' min='0' max='120' oninput='syncS(\"n_timer4\", this.value)'><input type='number' id='n_timer4' min='0' max='120' oninput='syncS(\"r_timer4\", this.value)'></div>\n"
"      </div>\n"
"      <div class='section'><h3>" kFwTitle "</h3>\n"
"        <span class='note'>" kFwNote "</span>\n"
"        <label>" kFwLabel "</label><input type='text' name='fwScheds'>\n"
"        <button type='button' onclick='reqCmd(\"/test-fireworks\")' class='btn-small' style='background:#f39c12;width:100%;margin-top:10px;'>" kFwTestBtn "</button>\n"
"      </div>\n"
"    </div></div>\n"
"\n"
"    <div id='tab_spinner' class='tab-content'><div class='grid'>\n"
"      <div class='section'><h3>" kSpinTitle "</h3>\n"
"        <label>" kSpinMin2 "</label><input type='number' name='spinMin' min='0' max='9999'>\n"
"        <label>" kSpinMax2 "</label><input type='number' name='spinMax' min='1' max='9999'>\n"
"        <label>" kSpinDur2 "</label><div class='sg'><input type='range' id='r_spinDur' name='spinDur' min='1' max='30' oninput='syncS(\"n_spinDur\", this.value)'><input type='number' id='n_spinDur' min='1' max='30' oninput='syncS(\"r_spinDur\", this.value)'></div>\n"
"      </div>\n"
"      <div class='section'><h3>" kSpinManualTitle "</h3>\n"
"        <button type='button' onclick='doSpin(this)' class='btn-small' style='background:#28a745;width:100%;margin-bottom:10px;'>" kSpinBtn "</button>\n"
"        <button type='button' onclick='doSpinReset(this)' class='btn-small' style='background:#dc3545;width:100%;'>" kSpinReset "</button>\n"
"      </div>\n"
"    </div></div>\n"
"\n"
"    <div id='tab_ota' class='tab-content'><div class='grid'>\n"
"      <div class='section'><h3>" kOtaTitle "</h3>\n"
"        <span class='note'>" kOtaNote "</span>\n"
"        <input type='file' id='firmwareInput' accept='.bin' style='padding:10px;border:1px dashed #0056b3;border-radius:8px;'>\n"
"        <button type='button' onclick='uploadFirmware()' class='btn-small' style='background:#28a745;margin-top:10px;width:100%;'>" kOtaBtn "</button>\n"
"        <progress id='uploadProgress' max='100' value='0'></progress>\n"
"        <span id='statusMsg' style='display:block;margin-top:5px;font-weight:bold;'></span>\n"
"      </div>\n"
"    </div></div>\n"
"\n"
"  </form>\n"
"</div>\n"
"</body></html>\n"
"\n";

